dist: trusty
sudo: required
group: edge

language: python

python:
    - "3.5"

cache: pip

install:
    # install protobuf
    - sudo bash scripts/install/travis_install.bash

    # install python dependencies
    - pip install -r requirements.txt
    - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl

    # install c++ lib for wavedata
    - sudo bash scripts/install/build_integral_image_lib.bash

before_script:
    - git submodule init
    - git submodule update
    - export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/wavedata
    - sudo protoc avod/protos/*.proto --python_out=.

script:
    - python scripts/preprocessing/travis_test_preprocessing.py
    - python -m unittest discover -b --pattern "*_test.py"

notifications:
    email: false
